### ISSUE TITLE
Not working in Safari

### ISSUE THREAD

**Issue by mrenty** [benhowdle89/grade#1]
First of all very nice stuff!
But sadly it isn't working in Safari (Version 9.1.2 (10601.7.7)).
I think because you aren't passing any percentages for the gradient.
Maybe this can be solved by just setting the two colours of the gradient as `data-attributes` and then read them via CSS so you have less inline styles and better cross-browser implementation.

**Comment by benhowdle89** [comment]
Fixed, check it out!
