### ISSUE TITLE
Canva tainted by cross-origin data on Chrome

### ISSUE THREAD

**Issue by Barthoware** [benhowdle89/grade#11]
Hi !
I downloaded Grade to try it out and when I opened /docs/index.html on Chrome, the backgrounds behind the images are staying white. On the console I got this error :

> grade.js:39 Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.

My Chrome version is  52.0.2743.116 m

This is however working fine on Firefox 44.0.2

**Comment by benhowdle89** [comment]
Hey, sorry to hear this. Hopefully the new sections in the [README](https://github.com/benhowdle89/grade#running-locally) might help!
