### ISSUE TITLE
Request: ability to get just colors

### ISSUE THREAD

**Issue by hellsan631** [benhowdle89/grade#14]
Really like the concept, what would you think about having a method that stops before rendering out the wrapper, and just gets the 2 dominant colours in the image?

**Comment by DarrylD** [comment]
I too think it would be nice to have access to the colors. I want to use them outside of just the wrapper.  Maybe id each element and set a global object for them?

**Comment by DarrylD** [comment]
@hellsan631 i did notice the colors are available in localstorage https://github.com/benhowdle89/grade/blob/master/src/index.js#L113

**Comment by benhowdle89** [comment]
Good idea.

My proposed usage:

```
Grade(imageContainers, imageSelector, function(gradients){
    // structure of `gradients`
    [{
        element: <Node>,
        data: // gradient data
    }]
})
```

You could then loop through `gradients` and get access to each image container that you passed in, along with the corresponding gradient data. Sound good?

**Comment by benhowdle89** [comment]
Done, check it out:

ada9063f7f64378ded6947beec235afd4eef8532

The README has been updated for full usage details...
