### ISSUE TITLE
Suggestion: Generate recommended text color

### ISSUE THREAD

**Issue by pentool** [benhowdle89/grade#15]
This looks promising! The only suggestion I have is to somehow generate/suggest text color (either black or white) based on the generated gradient.

Chances are you might want to have text under/above the image(s). If the resulting gradient is dark, you can't use dark text. If the gradient ends up being light, you can't use light text.

But it might be hard to know (especially if you get the images from a service) whether the gradient will end up being light or dark. So, depending on the gradient, somehow it would also "return" either black or white for text color, depending on which would be best readable on the gradient itself.

Of course if the black level of the gradient would end up being around 50% gray, then that's a tough one.

**Comment by brysont** [comment]
I have to agree with @pentool. I'd like to see that added to this to make it a complete solution. But a short-term solution is to just box the text, maybe with opacity to allow the underlying gradient to show through, and still control some of how a single, standard text color shows on top of it.

**Comment by benhowdle89** [comment]
A text colour is now also added as a CSS property to the container, depending on the darkness/lightness of the output gradient: https://github.com/benhowdle89/grade/commit/39e11e0016aca800bd58881fb8f91dcce3433b2b
