### ISSUE TITLE
This is just...broken

### ISSUE THREAD

**Issue by danielfonda** [benhowdle89/grade#3]
Cannot get the darn thing to work for the life of me. Just generates an error..specifically this: "Uncaught ReferenceError: module is not defined" line 103

**Comment by nijikokun** [comment]
How are you trying to use the module?

**Comment by danielfonda** [comment]
I'm actually trying to use it with Wordpress. I've renamed the resource .js file to grade.js
Enqueued the file in the header (which shouldn't be an issue, seeing as other .js files run fine).
I've then added this (before the opening footer tag):
`<script type="text/javascript">
    window.addEventListener('load', function(){
        /*
            A NodeList of all your image containers (Or a single Node).
            The library will locate an <img /> within each
            container to create the gradient from.
         */
        Grade(document.querySelectorAll('.thumbnail_grad'))
    })
</script>`

This results in the aforementioned error and just ends up not working.

Let me add that js hint (Atom) - also outputs a bunch of errors (most of them following this example):
"W104 - 'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).at line 1 col 1"

**Comment by nijikokun** [comment]
You're going to want to compile it for browser usage, not rename it.

``` js
babel src/index.js --out-file grade.js
```

**Comment by benhowdle89** [comment]
Hey Daniel,

From the README:

> Download this repo and grab the grade.js file from the /docs/dist folder.

So you shouldn't need to compile anything, just copy that file into your project and reference it from a script tag,

Hope this helps

**Comment by danielfonda** [comment]
@benhowdle89 @nijikokun Thanks for the help - will try again and let you know how it goes.
Only issue that I may have however, is that the index.html file is the docs folder results in the following:
http://www.awesomescreenshot.com/image/1504079/927134018a4ee807d78acd196ed720ac

In other words - I don't think it works in the example provided in the download folder.

**Comment by kgengler** [comment]
you're probably seeing the same problem as issue #5

**Comment by danielfonda** [comment]
Does this require a web server to work? I'll test it out and report back.

**Comment by danielfonda** [comment]
I can confirm that it works with wamp - launched from a server, rather than desktop.

**Comment by benhowdle89** [comment]
Excellent, glad you got it working!

**Comment by clooth** [comment]
@benhowdle89 Just a quick question, why don't you compile a transpiled module before deploying to npm and just set `"main": "lib/index.js"`? Then you wouldn't need to have babel when using the package.
