### ISSUE TITLE
OSX Google Chrome - SecurityError

### ISSUE THREAD

**Issue by MrSrsen** [benhowdle89/grade#5]
I'am getting this error in sample (Chrome osx). I did not change anything:
"grade.js:38 Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data."

Full error object:

```
grade.js:38 Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
    getImageData @ grade.js:38
    render @ grade.js:111
    readImage @ grade.js:33
    Grade @ grade.js:25
    (anonymous function) @ grade.js:121
    module.exports @ grade.js:120
    (anonymous function) @ index.html:109
```

**Comment by kgengler** [comment]
Did you just open the index.html in the browser? you're going to get a security error since there is no domain for the document.

try running `python -m SimpleHTTPServer 3000` in the docs directory and then visiting http://localhost:3000

**Comment by MrSrsen** [comment]
So this will not work without webserver?

**Comment by kgengler** [comment]
that would be the preferred method. otherwise see http://stackoverflow.com/questions/4409901/how-can-access-and-the-origin-policy-in-chrome-as-im-not-using-a-server

**Comment by danielfonda** [comment]
I can confirm that it works with wamp - launched from a server, rather than desktop.
