### ISSUE TITLE
Flash of Unstyled DIVs

### ISSUE THREAD

**Issue by vilbht** [benhowdle89/grade#8]
Hi there

Thanks for the plugin! love the simplicity. I understand that the images load up first and that the colors are derived from the images. But is there an ideal time to look out for. Seems to take 1-2s before the DIV colors fill in. Is that the normal performance of the div? Is there a way to work with an IMGIX api to reduce this time taken for the gradient to appear? Would love to get your thoughts.

Cheers

**Comment by benhowdle89** [comment]
It's a very good point! I have made some drastic performance improvements, so maybe check those out, then we can still see if there's an issue here 👍

**Comment by vilbht** [comment]
Whoa, that's a huge bump in performance! Thanks so much. Just to follow up, if image load times were minimized, then the gradients appearance could be sped up accordingly right?

**Comment by benhowdle89** [comment]
Absolutely. Gonna close for now if that's cool!
